# Generated by Django 4.2.6 on 2024-05-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0003_alter_aluno_senha_alter_professor_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id_aluno',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='id_professor',
        ),
    ]
