# Generated by Django 4.2.6 on 2024-05-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0004_remove_admin_id_aluno_remove_admin_id_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='esta_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
