# Generated by Django 4.2.6 on 2024-05-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0005_professor_esta_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='esta_ativo',
            new_name='ativo',
        ),
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
