# Generated by Django 4.2.6 on 2024-05-23 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0006_rename_esta_ativo_professor_ativo_aluno_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedacao.admin')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedacao.aluno')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedacao.professor')),
            ],
        ),
    ]
