# Generated by Django 4.2.6 on 2024-05-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0007_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_professor',
            new_name='id_prof',
        ),
    ]
