# Generated by Django 4.2.6 on 2024-05-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0009_aluno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aluno/'),
        ),
    ]
