# Generated by Django 5.0.2 on 2024-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0010_alter_aluno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
