# Generated by Django 5.0.2 on 2024-06-06 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0011_alter_professor_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redacoes',
            name='texto_redacao',
        ),
        migrations.AddField(
            model_name='correcao',
            name='id_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appRedacao.aluno'),
        ),
        migrations.AddField(
            model_name='redacoes',
            name='arquivo_redacao',
            field=models.FileField(blank=True, null=True, upload_to='redacoes/'),
        ),
    ]
