# Generated by Django 5.0.2 on 2024-06-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0012_remove_redacoes_texto_redacao_correcao_id_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaRedacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
            ],
        ),
    ]
