# Generated by Django 5.0.2 on 2024-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0013_temaredacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temaredacao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
