# Generated by Django 5.0.2 on 2024-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedacao', '0015_alter_redacoes_options_alter_redacoes_tema_redacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temaredacao',
            options={'verbose_name_plural': 'TemaRedacao'},
        ),
        migrations.RemoveField(
            model_name='temaredacao',
            name='tema',
        ),
        migrations.AddField(
            model_name='temaredacao',
            name='tema_redacao',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
